<?php 

	$getStores = ($block->getStores());
	$getStoreProduct = ($block->getStoreProduct());
	if(!empty($getStoreProduct)){
		$getStoreProductCount = count($block->getStoreProduct());	
	}
	

	// echo "<pre>";print_r($getStoreProduct);
	// for($i=1; $i<=4;$i++)	{

	if(!empty($getStores)){
		$count = 0;
		foreach($getStores as $stores){

			if(!empty($getStoreProductCount)){
				if($getStoreProductCount > $count){
					if($getStoreProduct[$count]){
						$getStoreProductValue = $getStoreProduct[$count];
					}
				}
			}else{
				$getStoreProductValue = '';
			}
			
			
			
	
?>
<p><input data-form-part="product_form" type="checkbox" name="typeofstore[]" value="<?php echo $stores['id']?>" <?php if($stores['id'] == $getStoreProductValue){ echo "checked"; }else{ echo "";}?> ><?php echo $stores['storestype']?></p>

<?php $count++ ;} ?>
<?php } ?>