<?php 
$categories = $block->getCategoryCollection();

                                	foreach ($categories as $category) { 
                                		// echo "<pre>";print_r($category->getImage());
                                  //       echo "<pre>";print_r($category->getImageUrl());
                                		?>
                                		<?php //if(!empty($_imgHtml)){ ?>
                                		<div class="imagesGridItem imagesGridItemHalf">
                                        <img src="<?php echo ($category->getImageUrl()) ?>" alt="" class="img-fluid"/>
                                        <div class="imagesGridItemOver">
                                        <h4>
                                            <span><?php echo $category->getName() ?></span>
                                            <!-- <b>bags</b> -->
                                        </h4>
                                        <button class="btn btn-outline-light">
                                            <span><a href="<?php echo $category->getUrl()?>">shop now</a></span>
                                            <svg width="25" height="13" viewBox="0 0 25 13" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                <path d="M24.5493 5.75435C24.549 5.75407 24.5487 5.75374 24.5484 5.75346L19.6498 0.878465C19.2828 0.513263 18.6892 0.514622 18.3239 0.881653C17.9587 1.24864 17.9601 1.84221 18.3271 2.20746L21.616 5.48046L1.76172 5.48046C1.24394 5.48046 0.824219 5.90018 0.824219 6.41796C0.824219 6.93574 1.24394 7.35546 1.76172 7.35546L21.616 7.35546L18.3271 10.6285C17.9601 10.9937 17.9587 11.5873 18.324 11.9543C18.6893 12.3213 19.2829 12.3226 19.6498 11.9575L24.5485 7.08246C24.5487 7.08218 24.549 7.08185 24.5493 7.08157C24.9165 6.7151 24.9153 6.1196 24.5493 5.75435Z" fill="white"></path>
                                            </svg>
                                        </button>
                                        </div>
                                    </div>
                                	<?php //} ?>
                                	<?php } ?>
                                	