<form method="post" action="<?php echo $this->getUrl().'quote/submit/quotation'?>">
	<p>Full Name: <input type="text" name="fullName"></p>
	<p>Email: <input type="text" name="emailAddress"></p>
	<p>Phone Number: <input type="text" name="phoneNumber"></p>
	<p>Quantity: <input type="text" name="quantity"></p>
	<p>Product Detail: <input type="text" name="productDetail"></p>
	<p>Project Description: <textarea name="projectDescription"></textarea></p>
	<p><button type="submit" name="requestQuote">Request a Quote</button></p>
</form>