 <?php
//          $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
//          $customerSession = $objectManager->get('\Magento\Customer\Model\Session');
//         $test = $customerSession->getCustomer()->getPasswordHash();
//         echo $test;
// die();
 ?>
 <!-- MainBodyWrap -->
 <main class="main">
 <div class="loading-mask" style="display:none;" data-role="loader" ><div class="loader">
    <img alt="Loading..." src="<?php echo $block->getViewFileUrl('images/loader-2.gif') ?>"><p>Please wait...</p></div></div>
        <section class="manageAccount manageAccountPassword">
            <div class="container addPadding">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item"><a href="#">Manage account</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Password</li>
                    </ol>
                </nav>
                <div class="manageAccountTop">
                    <h4>Manage account</h4>
                </div>
                <div class="manageAccountRow">
                    <div class="manageAccountLeftBar">
                        <ul>
                        <li><a href="<?php echo $block->getBaseUrl(); ?>customer/account/edit">Profile</a></li>
                            <li><a href="<?php echo $block->getBaseUrl(); ?>customer/account/password" class="active">Password</a></li>
                            <li><a href="<?php echo $block->getBaseUrl(); ?>sales/order/history" >Orders</a></li>
                            <!-- <li><a href="#">Your customized design</a></li>
                            <li><a href="#">Notification settings</a></li> -->
                        </ul>
                    </div>
                    <div class="manageAccountRightBar">
                        <div class="manageAccountRightBarTop">
                            <h4>Update password</h4>
                        </div>
                        <!-- <form action="<?= $block->escapeUrl($block->getUrl('profile/account/change')) ?>"
                         method="post" id="form-validate"
                         enctype="multipart/form-data"
                         data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
                           autocomplete="off"> -->
                           <div class="response-msg" style="width:auto;"></div>
                           <form class="change-password-form" method="POST">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <input type="password" class="form-control" placeholder="Password"
                                            name="current_password" id="current_password" />
                                    </div>
                                    <div class="form-group">
                                        <input type="password" class="form-control" placeholder="New password" name="new_password" id="new_password"/>
                                        <!-- <span class="passwordInfoIcon">
                                            <svg width="16" height="16" viewBox="0 0 16 16" fill="none"
                                                xmlns="http://www.w3.org/2000/svg">
                                                <path
                                                    d="M8 0C3.58217 0 0 3.58182 0 7.99965C0 12.4178 3.58217 16 8 16C12.4178 16 16 12.4178 16 7.99965C16 3.58182 12.4182 0 8 0ZM9.22293 12.3679C9.22293 13.0387 8.67362 13.5824 8.00349 13.5824C7.33301 13.5824 6.78406 13.0387 6.78406 12.3679V7.05435C6.78406 6.38387 7.33301 5.84015 8.00349 5.84015C8.67362 5.84015 9.22293 6.38352 9.22293 7.05435V12.3679ZM8 4.83688C7.26003 4.83688 6.66009 4.23694 6.66009 3.49732C6.66009 2.757 7.26003 2.15775 8 2.15775C8.73962 2.15775 9.33991 2.757 9.33991 3.49732C9.33991 4.23694 8.73962 4.83688 8 4.83688Z"
                                                    fill="#A8A8A8" />
                                            </svg>
                                            <div class="icon-detail">
                                            Password must contain at least one number and one uppercase and lowercase letter and special character, and at least 8 or more characters.
                                            </div>
                                        </span> -->
                                    </div>
                                    <div class="form-group">
                                        <input type="password" class="form-control" placeholder="Confirm password" name="confirm_password" id="confirm_password" />
                                    </div>
                                </div>
                            </div>
                            <div class="manageAccountRightBarBtn d-flex align-items-center">
                                <button class="btn btn-primary d-flex align-items-center">
                                    <span>Save</span>
                                    <svg width="24" height="13" viewBox="0 0 24 13" fill="none"
                                        xmlns="http://www.w3.org/2000/svg">
                                        <path
                                            d="M23.725 5.83638C23.7248 5.8361 23.7245 5.83577 23.7242 5.83549L18.8256 0.960497C18.4586 0.595294 17.865 0.596653 17.4997 0.963684C17.1345 1.33067 17.1359 1.92425 17.5028 2.28949L20.7918 5.56249L0.9375 5.56249C0.419719 5.56249 0 5.98221 0 6.49999C0 7.01777 0.419719 7.43749 0.9375 7.43749L20.7917 7.43749L17.5029 10.7105C17.1359 11.0757 17.1345 11.6693 17.4998 12.0363C17.8651 12.4034 18.4587 12.4046 18.8256 12.0395L23.7242 7.16449C23.7245 7.16421 23.7248 7.16388 23.7251 7.1636C24.0923 6.79713 24.0911 6.20163 23.725 5.83638Z"
                                            fill="white" />
                                    </svg>
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </main>

    <script type="text/javascript">
        require(['jquery', 'bootstrap4'], function($) {
            $('.change-password-form').submit(function(e){
                $(".loading-mask").show();
                var passwordVal = $('#current_password').val();
                  var regularExp = /^(?=.*\d)(?=.*[!@#$%^&*])(?=.*[a-z])(?=.*[A-Z]).{8,}$/;
                  if(!regularExp.test(passwordVal)){
                    $('.response-msg').html("<div class='notify error'><h6>Current password must contain at least one number and one uppercase and lowercase letter and special character, and at least 8 or more characters.</h6></div>");
                    $(".loading-mask").hide();
                    return false;
                  }

                var passwordVal = $('#new_password').val();
                  var regularExp = /^(?=.*\d)(?=.*[!@#$%^&*])(?=.*[a-z])(?=.*[A-Z]).{8,}$/;
                  if(!regularExp.test(passwordVal)){
                    $('.response-msg').html("<div class='notify error' ><h6>New password must contain at least one number and one uppercase and lowercase letter and special character, and at least 8 or more characters.</h6></div>");
                    $(".loading-mask").hide();
                    return false;
                  }


                // if(($('#new_password').val()) != ($('#confirm_password').val())) {
                //   $('.response-msg').html("<div class='notify error' style='width:auto;'><h6>Password and confirm password should be same.</h6></div>");
                //   return false;

                // }
                var Url = "<?php echo $block->getUrl('profile/account/change') ?>";
                var formData = getFormData($(this));
                $.ajax({
                    type: "POST",
                    url: Url,
                    data: formData,
                    dataType: "json",
                    success: function(data) {
                        showResponse(data);
                        if(data.errors) {
                            // loginButton.text(loginText);
                            // loginButton.removeAttr('disabled');
                            $(".loading-mask").hide();

                        } else {
                             window.location.href = "<?php echo $this->getUrl().'customer/account/password'?>";
                        }

                    }
                });
                return false;
            });
            
            


            function getFormData(formElem){
                var unindexed_array = formElem.serializeArray();
                var indexed_array = {};

                jQuery.map(unindexed_array, function(n, i){
                    indexed_array[n['name']] = n['value'];
                });

                return indexed_array;
            }

            function showResponse(data) {
                if(data.errors) {
                    $('.response-msg').html("<div class='notify error' style='width:auto;'><h6>"+data.message+"</h6></div>");
                } else {
                    $('.response-msg').html("<div class='notify success' style='width:auto;'><h6>"+data.message+"</h6></div>");
                }
                setTimeout(function(){ $('.response-msg').html(null); }, 5000);
            }

 
   });
    </script>