<?php //echo $this->getImagePath();die; ?>
<style>

  .firstLineClass{
    
    margin-top: -25%;
    align-items: center;
    margin-left: 10%;
    font-family: fantasy;
    font-size: large;
    width: 20%;
    overflow-y: hidden;
  }

    .secondLineClass{
    
    margin-top: -27%;
    align-items: center;
    margin-left: 10%;
    font-family: fantasy;
    font-size: large;
    width: 20%;
    overflow-y: hidden;
  }
#regForm {
  background-color: #ffffff;
  margin: 100px auto;
  padding: 40px;
  width: 70%;
  min-width: 300px;
}

/* Style the input fields */
input {
  padding: 10px;
  width: 100%;
  font-size: 17px;
  font-family: Raleway;
  border: 1px solid #aaaaaa;
}

/* Mark input boxes that gets an error on validation: */
input.invalid {
  background-color: #ffdddd;
}

/* Hide all steps by default: */
/*.tab {
  display: none;
}*/

/* Make circles that indicate the steps of the form: */
.step {
  height: 15px;
  width: 15px;
  margin: 0 2px;
  background-color: #bbbbbb;
  border: none;
  border-radius: 50%;
  display: inline-block;
  opacity: 0.5;
}

/* Mark the active step: */
.step.active {
  opacity: 1;
}

/* Mark the steps that are finished and valid: */
.step.finish {
  background-color: #4CAF50;
}
</style>
<!-- <div class="row">
    <div class="col-md-8">
        <form name="addData" method="post" id="addData" class="form" action="<?php echo $this->getFormAction(); ?>" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
         data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
            <legend class="legend"><span>Vendor Registration</span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label" for="vendorEmail"><span>email</span></label>
                            <div class="control">
                            <input name="vendorEmail" id="vendorEmail" title="Vendor Email" value="" class="input-text" type="email" data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field required">
                            <label class="label" for="vendorPassword"><span>content</span></label>
                            <div class="control">
                                <input name="vendorPassword" id="vendorPassword" title="Vendor Password" value="" class="input-text" type="password" data-validate="{required:true}">
                            </div>
                        </div>
                        
                    </div>
            </fieldset>
            </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action submit primary" title="Save"><span>Save</span></button>
            </div>
        </div>
        </form>
    </div>
</div> -->
<form  method="post" id="regForm" class="form"  action="<?php echo $this->getFormAction(); ?>" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" name="regForm" enctype="multipart/form-data">


<!-- One "tab" for each step in the form: -->

<div class="tab">

<h3>Store Information</h3>
what is the name of your online store
  <p><input  name="vendorStoreName"  placeholder="what is the name of your online store" oninput="this.className = ''"></p>
</div>

<div class="tab">

<h3>One last step for the store setup</h3>
  
  <p><label class="col-md-6 control-label">Design Text Line </label></p>
  <p><input style="width:50%" name="firstTagline"  placeholder="Your Design Text Line" oninput="this.className = ''" id="firstTagline"></p>

<label>Select Color</label>
  <select name="textColorSelector" id="textColorSelector">
    <option value="rgb(17, 0, 0)">Black</option>
    <option value="rgb(95, 69, 46)">Brown</option>
    <option value="rgb(166, 72, 38)">Burnt Orange</option>
    <option value="rgb(212, 32, 33)">Cardinal</option>
    <option value="rgb(56, 156, 255)">Columbia Blue</option>
    <option value="rgb(15, 69, 9)">Forest Green</option>
    <option value="rgb(255, 179, 0)">Gold</option>
    <option value="rgb(170, 170, 170)">Gray</option>
    <option value="rgb(255, 107, 179)">Hot Pink</option>
  </select>

<label>Select Font</label>
<select name="textFontSelector" id="textFontSelector">
    <option value="Arial">Arial</option>
    <option value="Times New Roman">Times New Roman</option>
    <option value="Times">Times</option>
    <option value="Courier New">Courier New</option>
    <option value="Verdana">Verdana</option>
    <option value="Imapact">Imapact</option>
    <option value="Palatino">Palatino</option>
    <option value="Bookman">Bookman</option>
    <option value="Tahoma">Tahoma</option>
    <option value="Trebuchet MS">Trebuchet MS</option>
    <option value="Arial Black">Arial Black</option>
    <option value="Comic Sans MS">Comic Sans MS</option>
  </select>  
   <!-- <img src="<?php //echo $block->getImagePath(); ?>" id="dummyProductImage" crossorigin="anonymous"> -->
  <canvas id="canvas"/>
  <canvas id="setDesignArea"/>
  <img src="" id="">
  <img src="" id="">
  <img src="" id="">
 
</div>


<!-- div class="tab">
Connect your account with Stripe

<a href="<?php //echo $this->getstripeUrl(); ?>" target="_blank">
    Click me
</a>
</div> -->
<label>upload your logo</label>
 <input type="file" name="Vendorlogo">
<input type="hidden" name="canvasFile" id="canvasFile">
<div style="overflow:auto;">
  <div style="float:right;">
    <!-- <button type="button" id="prevBtn" onclick="nextPrev(-1)">Previous</button> -->
    <input type="submit" id="nextBtn" value="Submit">
  </div>
</div>

<!-- Circles which indicates the steps of the form: -->


</form>
<script>


    var canvas = document.getElementById('canvas'),
    ctx = canvas.getContext('2d');

canvas.width  = 350;
canvas.height = 450;
// document.body.appendChild(canvas);

function sendToCanvas( ob ){
  console.log(ob);
  var canvas = document.getElementById('canvas'),
    ctx = canvas.getContext('2d');

canvas.width  = 350;
canvas.height = 450;
  var img = new Image();
  img.addEventListener('load', function(){
    ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
    ctx.font = ob.fontWeight+' '+ob.fontSize+' '+ob.fontFamily;
    ctx.textAlign = 'center';
    ctx.fillStyle = ob.color;
    ctx.fillText(ob.text, canvas.width/2, canvas.height/2.5, 130);
  });
  img.src = ob.image;

  var canvas  = document.getElementById("canvas");
  var dataURL = canvas.toDataURL();
  var canvasFile = document.getElementById('canvasFile');
  canvasFile.value = dataURL;
}

// Defaults
var cvsObj = {
    text       : "Your Design Text",
    image      : "<?php echo $block->getImagePath();?>",
    fontFamily : "Arial",
    fontWeight : "bold",
    fontSize   : "24px",
    color      : "rgb(17, 0, 0)"
};

sendToCanvas( cvsObj ); // Send default data on init

document.getElementById("firstTagline").addEventListener("input", function(){
  cvsObj.text = this.value; // Modify cvsObj text
  sendToCanvas( cvsObj );   // Send custom data on input
});

document.getElementById("textColorSelector").addEventListener("change", function(){
  cvsObj.color = this.value; // Modify cvsObj text
  cvsObj.text = document.getElementById("firstTagline").value;
  sendToCanvas( cvsObj );   // Send custom data on input
});
document.getElementById("textFontSelector").addEventListener("change", function(){
  cvsObj.fontFamily = this.value; // Modify cvsObj text
  cvsObj.text = document.getElementById("firstTagline").value;
  cvsObj.color = document.getElementById("textColorSelector").value;
  sendToCanvas( cvsObj );   // Send custom data on input
});

function setDesignArea(){
  var canvas  = document.getElementById("canvas");
  var dataURL = canvas.toDataURL();

  require(["jquery"],function($) {
        $(document).ready(function() {
            var canvas  = document.getElementById("canvas");
            var dataURL = canvas.toDataURL();
          $('#canvasFile').val(dataURL);
          });
  });
}

function init () {
  // set our config variables
  canvas = document.getElementById('setDesignArea')
  ctx = canvas.getContext('2d')

  // outlined square X: 50, Y: 35, width/height 50
  ctx.beginPath()
  ctx.strokeRect(50, 35, 50, 50)

  // filled square X: 125, Y: 35, width/height 50
  ctx.beginPath()
  ctx.fillRect(125, 35, 50, 50)
}

function readURL(input) {
  if (input.files && input.files[0]) {
    var reader = new FileReader();
    
    reader.onload = function(e) {
      $('#blah').attr('src', e.target.result);
    }
    
    reader.readAsDataURL(input.files[0]); // convert to base64 string
  }
}

$("#imgInp").change(function() {
  readURL(this);
});


// function textColorSelector(){
//   getValue = document.getElementById("textColorSelector").value;
//   cvsObj.text = document.getElementById("firstTagline").value;
//   cvsObj.color = getValue;
//   sendToCanvas( cvsObj );
// };



// require([ 'jquery', 'jquery/ui'], function($){ 
//   $(document).ready(function($) {
//       var canvas = document.getElementById('canvas');
//       // var dummyProductImage = document.getElementById('dummyProductImage'),
//       ctx = canvas.getContext('2d');
//       canvas.width = $('#dummyProductImage').width();
//       canvas.crossOrigin = "Anonymous";
//       canvas.height = $('#dummyProductImage').height();
//       console.log($('#dummyProductImage').get(0));
//       ctx.drawImage($('#dummyProductImage').get(0), 0, 0);
//       ctx.font = "36pt Verdana";
//       $(document).on('input','#firstTagline',function(){
//           //redraw image
//           ctx.clearRect(0,0,canvas.width,canvas.height);
//           ctx.drawImage($('#dummyProductImage').get(0), 0, 0);
//           //refill text
//           ctx.fillStyle = "red";
//           ctx.fillText($(this).val(),40,80,130);
//       });

//   });
// });



// require(['jquery', 'jquery/ui'], function(jQuery){
// var canvas = document.getElementById('canvas'),
//         ctx = canvas.getContext('2d');
// canvas.width = jQuery('#dummyProductImage').width();
// canvas.crossOrigin = "Anonymous";
// canvas.height = jQuery('#dummyProductImage').height();
// ctx.drawImage(jQuery('#dummyProductImage').get(0), 0, 0);
// ctx.font = "36pt Verdana";
// jQuery(document).on('input','#firstTagline',function(){
//     //redraw image
//     ctx.clearRect(0,0,canvas.width,canvas.height);
//     ctx.drawImage(jQuery('#dummyProductImage').get(0), 0, 0);
//     //refill text
//     ctx.fillStyle = "red";
//     ctx.fillText(jQuery(this).val(),100,200,130);
// });


// var canvas2 = document.getElementById('canvas2'),
//         ctx = canvas2.getContext('2d');
// canvas2.width = $('#dummyProductImage').width();
// canvas2.crossOrigin = "Anonymous";
// canvas2.height = $('#dummyProductImage').height();
// ctx.drawImage($('#dummyProductImage').get(0), 0, 0);
// ctx.font = "36pt Verdana";
// $(document).on('input','#secondTagline',function(){
//     //redraw image
//     ctx.clearRect(0,0,canvas2.width,canvas2.height);
//     ctx.drawImage($('#dummyProductImage').get(0), 0, 0);
//     //refill text
//     ctx.fillStyle = "yellow";
//     ctx.fillText($(this).val(),100,220,130);
// });
// });
// $('button').click(function(){
//     console.log(ctx.getImageData(50, 50, 100, 100));
// });




</script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-jcrop/0.9.15/css/jquery.Jcrop.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-jcrop/0.9.15/js/jquery.Jcrop.js"></script>
 <script>
  require([ 'jquery', 'jquery/ui'], function($) { 
            $(document).ready(function(){
                $('#canvas').Jcrop({
                    onSelect: function(c){
                        console.log(c);
                        console.log(c.x);
                        console.log(c.y);
                        console.log(c.w);
                        console.log(c.h);
                    }
                })
            })
            })
        </script>