<div class="login">
        <div class="outerContainer">
            <div class="row no-gutters">
                <div class="col-md-4">
                    <div class="leftWrap h-100 d-flex align-items-center justify-content-center ">
                         <div class="logo">
                         <img src="<?php echo $block->getViewFileUrl('images/logoLight.svg') ?>" alt="" class="img-fluid">
                        </div>
                    </div>
                </div>
                <div class="col-md-8">
                    <div
                        class="rightWrap text-center d-flex flex-column align-items-center justify-content-center h-100 ">
                        <div class="loginContent my-auto">
                            <div class="topHeadWrap">
                                <h1>Reset password</h1>
                                <p>Please change your password</p>
                            </div>
                            <div class="response-msg"></div>
                            <form class="reset-form" method="POST">
                            <input type="hidden" name="token" value="<?=$_GET['token']?>">

                                <div class="form-group">
                                    <input type="password" required id="password" name="password" class="form-control" placeholder="Password">
                                </div>

                                <div class="form-group">
                                    <input type="password" required id="confirm_password" name="confirm_password" class="form-control" placeholder="Confirm password">
                                </div>

                                <button type="submit" class="btn btn-primary submitBtn">
                                    Submit
                                    <svg class="ml-4" width="24" height="12" viewBox="0 0 24 12" fill="#fff"
                                        xmlns="http://www.w3.org/2000/svg">
                                        <path
                                            d="M23.725 5.33638C23.7248 5.3361 23.7245 5.33577 23.7242 5.33549L18.8256 0.460497C18.4586 0.0952939 17.865 0.096653 17.4997 0.463684C17.1345 0.830668 17.1359 1.42425 17.5028 1.78949L20.7918 5.06249L0.9375 5.06249C0.419719 5.06249 0 5.48221 0 5.99999C0 6.51777 0.419719 6.93749 0.9375 6.93749L20.7917 6.93749L17.5029 10.2105C17.1359 10.5757 17.1345 11.1693 17.4998 11.5363C17.8651 11.9034 18.4587 11.9046 18.8256 11.5395L23.7242 6.66449C23.7245 6.66421 23.7248 6.66388 23.7251 6.6636C24.0923 6.29713 24.0911 5.70163 23.725 5.33638Z" />
                                    </svg>
                                </button>
                            </form>

                        </div>

                        <div class="bottomText">
                            <p class="mb-0">Back to <a href="<?php echo $this->getUrl()?>"> <strong>login</strong> </a> </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        require(['jquery', 'bootstrap4'], function($) {
            $('.reset-form').submit(function(e){
                var passwordVal = $('#password').val();
                  var regularExp = /^(?=.*\d)(?=.*[!@#$%^&*])(?=.*[a-z])(?=.*[A-Z]).{8,}$/;
                  if(!regularExp.test(passwordVal)){
                    $('.response-msg').html("<div class='notify error'><h6>Password should be alphanumric and atleast 8 characters long.</h6></div>");
                    return false;
                  }


                if(($('#password').val()) != ($('#confirm_password').val())) {
                  $('.response-msg').html("<div class='notify error'><h6>Password and confirm password should be same.</h6></div>");
                  return false;

                }
                var Url = "<?php echo $block->getUrl('user/password/') ?>";
                var formData = getFormData($(this));
                $.ajax({
                    type: "POST",
                    url: Url,
                    data: formData,
                    dataType: "json",
                    success: function(data) {
                       // console.log(data);
                        showResponse(data);
                        if(data.errors) {
                            loginButton.text(loginText);
                            loginButton.removeAttr('disabled');
                        } else {
                             window.location.href = "<?php echo $this->getUrl()?>";
                        }
                    }
                });
                return false;
            });
            
            


            function getFormData(formElem){
                var unindexed_array = formElem.serializeArray();
                var indexed_array = {};

                jQuery.map(unindexed_array, function(n, i){
                    indexed_array[n['name']] = n['value'];
                });

                return indexed_array;
            }

            function showResponse(data) {
                // console.log(data);
                // console.log("data");
                if(data.errors) {
                    console.log(data.message);
                    $('.response-msg').html("<div class='notify error'><h6>"+data.message+"</h6></div>");
                } else {
                    console.log(data.message);
                    $('.response-msg').html("<div class='notify success'><h6>"+data.message+"</h6></div>");
                }
                setTimeout(function(){ $('.response-msg').html(null); }, 5000);
            }

 
   });
    </script>