<?php include('client-header.phtml'); ?>
	<div class="pageContainer">
                <section class="createCouponsGeneral sectionPage">
                    <div class="createNew d-flex flex-column flex1">
                        <div class="createNewNav">
                            <a href="#" class="active">General information</a>
                        </div>
                        <div class="flex1">
                            <div class="row">
                                <div class="col-md-10">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Promotion type
                                                    <small
                                                        class=" ml-2 textDarkOrange font-weight-bold">Required</small>
                                                </label>
                                                <!-- btn-select -->
                                                <div class="dropdown">
                                                    <button class="btn btn-select btn-select-white" type="button"
                                                        data-toggle="dropdown" aria-haspopup="true"
                                                        aria-expanded="false">
                                                        Percentage
                                                    </button>
                                                    <div class="dropdown-menu dropdown-menu-border">
                                                        <a class="dropdown-item active" href="#">Percentage</a>
                                                        <a class="dropdown-item" href="#">Fixed amount</a>
                                                        <a class="dropdown-item" href="#">Package</a>
                                                        <a class="dropdown-item" href="#">Buy x get y</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Select store
                                                    <small
                                                        class=" ml-2 textDarkOrange font-weight-bold">Required</small>
                                                </label>
                                                <!-- btn-select -->
                                                <div class="dropdown">
                                                    <button class="btn btn-select btn-select-white" type="button"
                                                        data-toggle="dropdown" aria-haspopup="true"
                                                        aria-expanded="false">
                                                        Cmyk house
                                                    </button>
                                                    <div class="dropdown-menu dropdown-menu-border">
                                                        <div class="dropdown-item">
                                                            <label class=" customCheckBox d-flex align-items-center">
                                                                <input type="checkbox" checked>
                                                                <span class="customCheckBoxCheck"></span>
                                                                <span>Cmyk house</span>
                                                            </label>
                                                        </div>
                                                        <div class="dropdown-item">
                                                            <label class=" customCheckBox d-flex align-items-center">
                                                                <input type="checkbox">
                                                                <span class="customCheckBoxCheck"></span>
                                                                <span>Falcom crest</span>
                                                            </label>
                                                        </div>
                                                        <div class="dropdown-item">
                                                            <label class=" customCheckBox d-flex align-items-center">
                                                                <input type="checkbox">
                                                                <span class="customCheckBoxCheck"></span>
                                                                <span>Atlas print zone</span>
                                                            </label>
                                                        </div>
                                                        <div class="dropdown-item">
                                                            <label class=" customCheckBox d-flex align-items-center">
                                                                <input type="checkbox">
                                                                <span class="customCheckBoxCheck"></span>
                                                                <span>Castle print</span>
                                                            </label>
                                                        </div>
                                                        <div class="dropdown-item">
                                                            <label class=" customCheckBox d-flex align-items-center">
                                                                <input type="checkbox">
                                                                <span class="customCheckBoxCheck"></span>
                                                                <span>Layer studio</span>
                                                            </label>
                                                        </div>
                                                        <div class="dropdown-item">
                                                            <label class=" customCheckBox d-flex align-items-center">
                                                                <input type="checkbox">
                                                                <span class="customCheckBoxCheck"></span>
                                                                <span>Dc merch</span>
                                                            </label>
                                                        </div>
                                                        <div class="dropdown-item">
                                                            <label class=" customCheckBox d-flex align-items-center">
                                                                <input type="checkbox">
                                                                <span class="customCheckBoxCheck"></span>
                                                                <span>Luxe bros</span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
<?php include('client-footer.phtml'); ?>