<?php 
    $urlInterface = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\UrlInterface');
    $currentUrl = $urlInterface->getCurrentUrl();

    $explodeUrl = explode("/", $currentUrl);

    if(end($explodeUrl) == ""){
        // echo "<pre>";print_r(($explodeUrl));
        $countElements = count($explodeUrl);
        $arrayIndex  = ($countElements - 2);
        $getPageName = ($explodeUrl[$arrayIndex]);
    }else{
        $getPageName = end($explodeUrl);
    }
    // echo "<pre>";print_r(($explodeUrl));die;
    
    if ($getPageName == 'dashboard') {
        $pageName = "Dashboard";
    }elseif ($getPageName == 'sales') {
        $pageName = "Sales Report";
    }elseif ($getPageName == 'transactions') {
        $pageName = "Transactions Report";
    }elseif ($getPageName == 'promotions') {
        $pageName = "Promotions";
    }elseif ($getPageName == 'create') {
        $pageName = "Create";
    }elseif ($getPageName == 'stores') {
        $pageName = "Stores";
    }elseif ($getPageName == 'profile') {
        $pageName = "Stores";
    }elseif ($getPageName == 'add') {
        $pageName = "Create";
    }


    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $customerSession = $objectManager->create('Magento\Customer\Model\Session');

    if(($customerSession->isLoggedIn())){
        $name = $customerSession->getCustomer()->getName(); 
    }

?>

<div class="pageHeader">
                <div class="d-flex align-items-center">
                    <div class="flex1">
                        <h4><?php echo $pageName;?></h4>
                    </div>
                    <div class="d-flex align-items-center">
                        <div class="pageHeaderLinkChat">
                            <a href="#">
                                <!-- <h5>client support</h5> -->
                                <svg width="32" height="32" viewBox="0 0 32 32" fill="none"
                                    xmlns="http://www.w3.org/2000/svg">
                                    <circle cx="16" cy="16" r="16" fill="#FF7255" />
                                    <path
                                        d="M23.6432 16.2265C23.6432 20.4694 20.201 23.9177 15.9749 23.9177C15.1337 23.9177 14.3008 23.7785 13.5005 23.5081C11.8468 23.8726 10.1563 23.9341 9.19268 23.9341C8.71903 23.9341 8.42503 23.9177 8.38829 23.9177C8.21681 23.9095 8.0657 23.7907 8.01671 23.6269C7.96771 23.459 8.02897 23.2788 8.16778 23.1764L10.4176 21.526C9.0661 20.1049 8.30254 18.2005 8.30254 16.2265C8.30254 11.9837 11.7447 8.53125 15.9749 8.53125C16.3138 8.53125 16.6527 8.55175 16.9835 8.59679C20.201 9.0227 22.8102 11.4472 23.4798 14.6293C23.586 15.1494 23.6432 15.6859 23.6432 16.2265Z"
                                        fill="white" />
                                </svg>
                            </a>
                        </div>
                        <div class="btn-group dropdownUser">
                            <button type="button" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                                aria-expanded="false">
                                <img src="<?php echo $block->getViewFileUrl('User_Client::images/userImg.png'); ?>" alt="userImg" />
                                <?php if(!empty($name)){ ?>
                                <b><?php echo ucwords($name); ?></b>
                            <?php }else{ ?>
                                   <b>Login</b> 
                            <?php } ?>
                            </button>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a href="<?php echo $block->getBaseUrl(); ?>">Go to supertee website</a>
                                <a href="#">Manage account</a>
                                <a href="<?php echo $block->getBaseUrl(); ?>customer/account/logout"><button>Logout</button></a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>