<style type="text/css">
body {
    margin: 0;
}
* {
    box-sizing: border-box;
}
.container {
    max-width: 1200px;
    padding: 0 15px;
    margin: 0 auto;
}
.formRow {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    /*-webkit-box-align: center;*/
    /*-ms-flex-align: center;*/
    /*align-items: center;*/
}
.formRowCol {
    /* width: 50%; */
    padding: 0 15px;
}
.formRowColLeft {
    width: 60%;
}
.formRowColRight {
    width: 40%;
}
input {
    width: 100%;
    margin: 10px;
    padding: 10px 15px;
    border-radius: 15px;
    outline: 0;
    border: 1px solid #e0e0e0;
}
.imgFull {
    width: 100%;
    display: block;
}
.productImage {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
}
.productImageAction {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    max-height: 200px;
    overflow: auto;
    padding: 5px;
    background-color: rgba(0, 0, 0, 0.8);
    margin-bottom: 30px;
}
.productImageActionItem {
    background-color: #eee;
    width: 92px;
    height: 92px;
    margin-bottom: 10px;
    cursor: pointer;
    padding: 10px;
    margin: 4px;
}
.productImageView {
    width: -webkit-calc(100% - 150px);
    width: calc(100% - 150px);
    margin-left: 100px;
    position: relative;
}
.productImageViewOver {
    position: absolute;
    top: 130px;
    left: 0;
    right: 0;
    width: 180px;
    margin: auto;
    text-align: center;
}
.productImageViewOver img {
    max-width: 100%;
    margin: 0;
    /* display: block; */
    margin: 0 auto;
}
.productImageViewOver img:empty {
    /* display: none; */
}
.borderTopImg, .borderBottomImg, .logoImg {
    display: none;
}
.style4 .borderTopImg, .style4 .borderBottomImg {
    display: block;
}
.style4 .logo {
    display: none;
}
.style3 .logoImg {
    display: block;
}





.productImageViewAction {
    width: 70px;
    position: absolute;
    top: 70px;
    left: -150px;
}
.productImageViewActionItm {
    width: 100%;
    text-align: center;
    margin-bottom: 10px;
    padding: 10px;
    border: 1px solid #e0e0e0;
    cursor: pointer;
}
.productImageViewAction img {
    width: 50px;
    height: 50px;
    object-fit: contain;
    object-position: center;
}

.contentRow {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    margin-left: -15px;
    margin-right: -15px;
    width: -webkit-calc(100% + 30px);
    width: calc(100% + 30px);
}
.contentRow > div {
    padding-left: 15px;
    padding-right: 15px;
}
.contentRowCol40 {
    width: 40%;
}
.contentRowCol50 {
    width: 50%;
}
.contentRowCol60 {
    width: 60%;
}

/*.wrapper { position: relative }
    .imgFull {
        position: absolute; left: 0; top: 0; 
    }*/
</style>
<?php $product_id = ($this->request->getParams()['id']);?>

<div style="padding: 100px 0;">
        <div class="container">
            <div class="formRow">
            	<div class="formRowCol formRowColLeft">
                    <div class="productImage">
                        <div class="productImageView">
                            <div class="productImageViewAction">
                            	<?php 
                            	$count = 1;
                            	foreach($block->getAllProductImages($product_id) as $images){
                            		?>
                                <div class="productImageViewActionItm">
                                    <img src="<?php echo $images['url'];?>" id="side_<?php echo $count; ?>" data-side ="<?php echo $images['url'];?>"/>
                                </div>
                                <?php $count ++ ; 
                            } ?>
                            </div>
<!--                            
                            <div class="wrapper"> -->
<!-- 							 <canvas id="canvas" class="imgFull" width="700" height="700"></canvas>
 -->                             
 <canvas id="canvas" width="500" height="500" style="border:2px solid black"></canvas>
 <input type="radio" name="arrowQuestion" id="text" value="Text" >Add Text
 <br>

 							 <canvas id="canvasBack" class="imgFull" width="700" height="700"></canvas>
							 <canvas id="canvasLeft" class="imgFull" width="700" height="700"></canvas>
							 <canvas id="canvasRight" class="imgFull" width="700" height="700"></canvas>
							 <canvas id="innerCanvas" class="imgFull" width="700" height="700"></canvas>
<!-- 							</div>
 -->
                            <img src="<?php echo $block->getProductImage($product_id);?>" alt="img1" class="imgFull"
                                id="imgViewFull" style="display: none"/>
                            <div class="productImageViewOver">
                                <!-- <div>
                                    <img src="./assets/images/borderTop.png" />
                                    <img src="./assets/images/actionLogoImg3.png" />
                                    <div class="text1">text1</div>
                                    <img src="./assets/images/actionLogo3.png" />
                                    <div class="text2">text1</div>
                                    <img src="./assets/images/borderBottom.png" />
                                </div> -->
                            </div>
                        </div>
                    </div>
                </div>
                <!-- <div class="formRowCol">
                    <div>
                        <b>Textline:</b></p>
                        <input type="text" id="getTaglines" value="<?php //echo ($block->getTaglines());?>" disabled> 
                    </div>
                        <input type="text" id="text2">
                    </div> 
                </div-->

                <div class="formRowCol formRowColRight">
                    <div class="productImage">
                        <div class="productImageAction">


                            <div class="productImageActionItem" data-id="1" data-image1 = '<?php echo $block->getImagePath();?>actionLogo1.png' data-image1W = "163" data-image1H = "21" img1CdntX = "100" img1CdntY = "100" id="temp1">
                            	<!-- <a href="#">Add Text</a> -->
                                
                            </div>
                            <div class="productImageActionItem" data-id="2" data-image1 = '<?php echo $block->getImagePath();?>actionLogo2.png' data-image1W = "163" data-image1H = "42" id="temp2">
                                <a href="#">Add Image</a>
                            </div>


                            <div class="productImageAction side_view onlyChar" data-id="5" id="paramName" style="display: none">
                          Name
                        </div>
                        <div class="productImageAction side_view onlyInt" data-id="6" id="paramNum" style="display: none">
                          00
                        </div>
                        <div class="productImageAction side_view alphaNumric" id="numName" data-id="6" style="display: none">
                          Name 00
                        </div>
                        </div>
                        <input type="text" name="addNumber" id="addNumber" disabled="" value="00">
                        <input type="text" name="addName" id="addName" disabled="" value="My Name">
                        <div class="productImageView">
                        	
                            <img src="<?php echo $block->getProductImage($product_id);?>" alt="img1" class="imgFull" style="display: none"/>
                            <div class="productImageViewOver">
                            </div>
                        </div>
                        
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    
    <?php 
const PARAM_NAME_BASE64_URL = 'r64';
const PARAM_NAME_URL_ENCODED = 'uenc';
use Magento\Framework\App\Action\Action; 
$_productCollection = $block->getProductCollection();
?>
<?php foreach ($_productCollection as $_product): ?>
	<?php if($product_id == $_product->getId()){ ?>
    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
    <?php echo $_product->getName()?>
    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
        <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
        <?php echo $block->getBlockHtml('formkey')?>
        <?php $storeManager = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Store\Model\StoreManagerInterface'); ?>
            <button type="submit"
                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                    class="action tocart primary">
                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
            </button>
    </form>
<?php } ?>
<?php endforeach;?>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/1.7.11/fabric.min.js"></script>
<script>
require(['jquery'], function($){

    $(document).ready(function() {
  	
        var arr = ["Roboto", "Open+Sans", "Lato", "Raleway", "Source+Sans+Pro", "Ubuntu", "Titillium+Web", "Poppins", "Dosis", "Nunito", "Work+Sans", "Cabin", "Josefin+Sans", "Merriweather+Sans", "Exo+2", "Source+Code+Pro", "Kanit", "Exo", "Rokkitt", "Martel", "Alegreya+Sans+SC", "Arima+Madurai", "Montserrat+Alternates", "Martel+Sans", "Expletus+Sans", "Inknut+Antiqua", 'Krona+One', 'Abril+Fatface', 'Courgette', 'Dancing+Script','Great+Vibes', 'Lobster+Two', 'Pinyon+Script', 'Satisfy'];
// function drawImage(){

// 	var fontFamily = arr[Math.floor(Math.random() * arr.length)];
// 	var link = document.createElement('link');
// 	link.rel = 'stylesheet';
// 	link.type = 'text/css';
// 	link.href = 'https://fonts.googleapis.com/css?family='+fontFamily;
// 	console.log(link);
// 	document.getElementsByTagName('head')[0].appendChild(link);


//     img = new Image();
    
//     img.onload = function(){
//     	var ctx = canvas.getContext('2d');
//         ctx.drawImage(img, 0, 0, 700, 700);
        
//         ctx.textAlign = 'center';
//         fontFamily.replace('+', ' ');

// 	      ctx.font = '40px Impact';
// 	      ctx.fillText("<?php //echo $block->getTaglines();?>", 350, 350);
//     };

//     img.src = "<?php //echo $block->getProductImage($product_id);?>";
// }

// drawImage();

var canvas = new fabric.Canvas('canvas');
// Define an array with all fonts
var fonts = ["Roboto", "Open+Sans", "Lato", "Raleway", "Source+Sans+Pro", "Ubuntu", "Titillium+Web", "Poppins", "Dosis", "Nunito", "Work+Sans", "Cabin", "Josefin+Sans", "Merriweather+Sans", "Exo+2", "Source+Code+Pro", "Kanit", "Exo", "Rokkitt", "Martel", "Alegreya+Sans+SC", "Arima+Madurai", "Montserrat+Alternates", "Martel+Sans", "Expletus+Sans", "Inknut+Antiqua", 'Krona+One', 'Abril+Fatface', 'Courgette', 'Dancing+Script','Great+Vibes', 'Lobster+Two', 'Pinyon+Script', 'Satisfy'];

// var canvas = new fabric.Canvas('canvas');

// load image
var canvas = new fabric.Canvas('canvas');
var canvasHeight=canvas.height;
var canvasWidth=canvas.width;

canvas.setBackgroundImage('http://fabricjs.com/assets/jail_cell_bars.png', canvas.renderAll.bind(canvas), {
    backgroundImageOpacity: 0.5,
    backgroundImageStretch: false
 });

canvas.on('mouse:down', function(options) {
    useText=document.getElementById("text").checked;
    if(useText)
        {
            addTextBox(options.e.clientX,options.e.clientY);
            useText=false;
            document.getElementById("text").checked=false;
        }
    else
        return;        
});

function addTextBox(arrowLeft,arrowTop)
{
    console.log('here')
    textBox=new fabric.Textbox("Enter Text",{
    fontSize: 16,
    fontFamily: 'Arial',
    textAlign: 'left',  
    width: 180, // for 20 characters
    top:arrowTop,
    left:arrowLeft
    });
    
      canvas.add(textBox);
  canvas.renderAll(); 

textBox.on('selected', function(e) {
        console.log(textBox);
        console.log('selected Textbox');
            canvas.renderAll();
        
});

textBox.on("editing:entered", function (e) {
                //canvas.setActiveObject(textBox);
                var obj = canvas.getActiveObject();
        console.log("entered editing");
        if(obj.text == "Enter Text")
        {
                obj.selectAll();
                obj.removeChars();
        }
});

textBox.on("editing:exited", function (e) {
        console.log("exited editing");
});
    var left = arrowLeft;

    textBox.on(("changed"),function(){
       //canvas.setActiveObject(textBox);
       var actualWidth = textBox.scaleX * textBox.width;
        var largest = canvas.getActiveObject().__lineWidths[0];
        var tryWidth = (largest + 15) * textBox.scaleX;
        canvas.getActiveObject().set("width",tryWidth);
        if((textBox.left + actualWidth) >= canvas.width - 10)
         {
             //console.log(canvas.height - arrowLeft)
             textBox.set("width", canvas.width - left - 10)
        }
            canvas.renderAll();

    });
    textBox.on(("modified"),function(){
      left = textBox.left;
      console.log("textbox modified");
            canvas.renderAll();

    });  
}
});
});
</script>